name: Generate for kotlin

on:
  push:
    paths:
      - .github/workflows/generate-for-kotlin.yaml
      - kotlin/**
      - OpenApi/**

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: kotlin


    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: |
          chmod a+x ./gradlew
          ./gradlew clean build
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test*/TEST-*.xml'
      - name: Upload kotlin-client artifact
        uses: actions/upload-artifact@v3
        with: 
          name: todoist-kotlin-client
          path: kotlin/generated/client/build/libs
      - name: Upload kotlin-server artifact
        uses: actions/upload-artifact@v3
        with: 
          name: todoist-kotlin-server-stub
          path: kotlin/generated/server/build/libs
            